project:
  type: book
  output-dir: docs

book:
  title: "OTESSA 2025 Online Conference Program"
  reader-mode: true
  date: "last-modified"
  date-format: "MMM D, YYYY [@] h:mm a z [(UTC]Z[)]"
  chapters:
    - index.qmd
    - jun02.qmd
    - jun03.qmd
    - jun04.qmd
    - jun05.qmd
    - jun06.qmd


comments:
  hypothesis: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-depth: 0
    toc-depth: 4
    mainfont: arial
    fontsize: "18px"
  pdf:
    documentclass: scrreprt
    title: "OTESSA 2024 Conference Program"
format-links: pdf


