# Monday, June 2 {.unnumbered}


## Times listed in this program are Pacific Daylight Time (Victoria, BC) 

:::: {.columns}

::: {.column width="33%"}
<div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
  <div class="card-header"><b><font size="5">Victoria, BC</font></b></div>
  <div class="card-body">
   <div> <iframe src="https://free.timeanddate.com/clock/i9wk0yr8/n1091/fs22/fcfff/tct/pct/ftb/ts1/ta1" frameborder="0" width="168" height="27" allowtransparency="true"></iframe>
</div>
  </div>
</div>

:::

::: {.column width="34%"}
<div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
  <div class="card-header"><b><font size="5">Santa Fe, NM</font></b></div>
  <div class="card-body">
   <div> <iframe src="https://free.timeanddate.com/clock/i9wk0yr8/n231/fs22/fcfff/tct/pct/ftb/ts1/ta1" frameborder="0" width="172" height="27" allowtransparency="true"></iframe>
</div>
  </div>
</div>


:::

::: {.column width="33%"}


<div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
  <div class="card-header"><b><font size="5">Toronto, ON</font></b></div>
  <div class="card-body">
   <div> <iframe src="https://free.timeanddate.com/clock/i9wk0yr8/n250/fs22/fcfff/tct/pct/ftb/ts1/ta1" frameborder="0" width="168" height="27" allowtransparency="true"></iframe>
</div>
  </div>
</div>

:::
::::


## 8:30 - 9:00 | Conference Welcome, Announcements, & Land Acknowledgement <!--(ask Jean-Paul to join??)--> {.unnumbered}

## 9:00 - 10:00 | Keynote: Peter Scott | Multi-Laterally Open: A Commonwealth Story

## 10:00 - 10:15 | Break

## 10:15 - 11:15 | Concurrent Session 1 

(60 Mins)


### Session 1.1

#### 10:15 - 11:05 | Time Barriers for Adopting Digital Tools in Language Teachers’ Practice

**Research**

**Maryam Elshafei** | *York University*

::: {.callout-note collapse="true"}
### Abstract
An entire sub-field within language teaching has emerged exploring how technology can be used to mediate language learning, yet the impact of using these technologies on teachers is rarely discussed. Institutions and researchers seem to echo the affordances of digital tools and their transformative potential for improving student outcomes. At the same time, they have been blaming teachers for not using technology to its full potential, framing teachers as lacking the skills or beliefs for not using educational technologies in their teaching (Ertmer & Ottenbreit-Leftwhich, 2010; Orlando, 2015). One of the major constraints that seems to be raised but dismissed in the literature is time. Teachers have expressed the lack of time over and over again, but there seems to be a lack of interest in addressing this problem (Atabek, 2019; Kopcha, 2012; Lawrence, 2018). Demanding teachers use their time to integrate edtech affects their personal and instructional time and their ability to exert agency over their time, and thus needs to be acknowledged and rewarded.
:::

### Session 1.2

#### 10:15 - 10:35 | Expectations for Generative AI Integration in Pedagogical Strategies

**Research**

**Enas Aref et al.** | *Western Michigan University*

::: {.callout-note collapse="true"}
### Abstract
The global interest in integrating Generative Artificial Intelligence (Gen AI) tools in education is on the rise. While such integration provides potential advantages for all elements of the educational procedures, yet several questions remain unanswered. These questions inquire about the effective utilization of those tools and how to integrate them with pedagogical strategies. In this research, we will conduct a scoping review to acquire information about the essential components to create suitable frameworks of AI-integrated tools within strategies, educators' perceptions of the usability of those frameworks, and the challenges and benefits of those frameworks. The findings will provide comprehensive insights that will benefit educators in understanding the effective ways to integrate AI tools with pedagogical strategies. Also, it will benefit students by providing them with appropriate instructional design that fits with their goals and meets their needs. In this presentation, the researchers will provide a comprehensive overview of this work in progress (WIP) project and will share some of the preliminary findings.
:::
 
### Session 1.3a 


#### 10:15 - 10:35 | Reframing Presence in Fully Online Learning: Embracing Imagination, the More-than-human, and Sustainability

**Practice**

**Susanna Kohonen** | *University of Eastern Finland*

::: {.callout-note collapse="true"}
### Abstract
In the context of fully online learning, higher education students have been found to struggle with feelings of isolation, lack of experience of presence, and lack of meaningful connections. These in turn have a negative effect on learning outcomes. To tackle these challenges, the presentation proposes drawing on posthumanist and socio-materialist thought. How to foster a sense of presence and togetherness in digital learning spaces is a question many online teachers, including myself, find challenging to answer. Are synchronous online sessions the only plausible option? This presentation aims to challenge our imagination by reflecting on both theoretical underpinnings and practical steps for educators to create more inclusive online learning environments that may enable opportunities for experiencing presence, ultimately aiming to reframe the concept of togetherness in fully online education.
:::

### Session 1.3b 

#### 10:35 - 10:55 | Modelling Students Emotional Trajectories in Course Evaluations: A Computational Framework for Enhancing Student Success

**Research**

**Christel Young et al.** | *East Tennessee State University*

::: {.callout-note collapse="true"}
### Abstract
This session introduces the Emotional Trajectory Model (ETM), a computational framework designed to explore the emotional dimensions of student feedback in high-enrollment, introductory courses. Drawing on data from six semesters of the Using Information Technology course at a large public university, this exploratory research captures student sentiment from end-of-semester evaluations to better understand how students emotionally engage with course content, instruction, and learning experiences.
:::

## 11:15 - 11:45 | Break
  
## 11:45 - 12:45 | Concurrent Session 2 

(60 Mins)

### Session 2.1

#### 11:45 - 12:35 | AI and Human-Centered Open Education: Sopala: An Innovative Model for K-12 Education

**Research**

**Sadik Shahadu et al.** | *Affiliation*

::: {.callout-note collapse="true"}
### Abstract
The proposed presentation is part two of a study shared in the June 2024 OTESSA conference and published in a proceedings paper. Author et al.’s (2023) review of the alignment between design principles (Crichton & Author, 2022) and the National Standards for Quality Online Learning (NSQOL 2019a, 2019b, & 2019c) and the Quality Matters standards (QM, 2016a, 2016b) concluded that most standards served as examples of components that could be found in an effective model or a course without a clear picture of what they comprise collectively. As the researchers found a stronger alignment with the research-based Quality Matters (QM, 2016a, 2016b) than the NSQOL standards, the Community of Inquiry (Garrison et al., 2000) was explored as the COI was used as a framework for the Standards for K-12 Online Learning in British Columbia (BC Ministry of Education, 2021). This session will focus on the alignment of the design principles with the COI’s thirty-four-question survey (Arbaugh et al., 2024). Reference will also be made to other quality frameworks, including the Quality Matters K-12 rubrics and instructor skills set (QM, 2016a, 2016b) and First Peoples Principles of Learning (FNESC, 2020).

The analysis led to a potential model to guide the development of engaging and supportive online learning that will be shared. Researchers also plan to share it with online educators and revise the model and the design principles. The design principles specific to post-secondary preparation, continuing research, and teacher well-being were not reflected in either the COI model or standards. Further research is required to determine intersection points between all three specific to online course design and instruction benchmarks.

It is hoped that basing the design principles in the context of research-based models will further develop an understanding of quality in K-12 online learning and inform K-12 online practice.
:::


### Session 2.2a

#### 11:45 - 12:05 | Exploring the Alignment of Design Principles for K-12 Online Learning with Researched Models and Standards: Principles to Guide Engaging and Supportive Online Learning

**Research**

**Randy LaBonte et al.** | *CANeLearn*

::: {.callout-note collapse="true"}
### Abstract
The proposed presentation is part two of a study shared in the June 2024 OTESSA conference and published in a proceedings paper. Author et al.’s (2023) review of the alignment between design principles (Crichton & Author, 2022) and the National Standards for Quality Online Learning (NSQOL 2019a, 2019b, & 2019c) and the Quality Matters standards (QM, 2016a, 2016b) concluded that most standards served as examples of components that could be found in an effective model or a course without a clear picture of what they comprise collectively. As the researchers found a stronger alignment with the research-based Quality Matters (QM, 2016a, 2016b) than the NSQOL standards, the Community of Inquiry (Garrison et al., 2000) was explored as the COI was used as a framework for the Standards for K-12 Online Learning in British Columbia (BC Ministry of Education, 2021). This session will focus on the alignment of the design principles with the COI’s thirty-four-question survey (Arbaugh et al., 2024). Reference will also be made to other quality frameworks, including the Quality Matters K-12 rubrics and instructor skills set (QM, 2016a, 2016b) and First Peoples Principles of Learning (FNESC, 2020).
:::

### Session 2.2b

#### 12:05 - 12:25 | Yes, You Can: Research With Adult Trauma Survivors Who Learn Online

**Practice**

**Hilary Schmidt** | *Thompson Rivers University*

::: {.callout-note collapse="true"}
### Abstract
Trauma-informed educational practices are rapidly gaining traction in higher education, with increasing interest from faculty and staff, administrators, and government policymakers. While the volume of scholarly publications in this area has increased over the past few years, literature on trauma-informed pedagogy and practice in higher education continues to consist primarily of practitioner reflections, with a paucity of empirical research (Anderson et al., 2023). As far as I am aware, my own publications (Schmidt, 2023, 2024, in press) comprise the first peer-reviewed research to examine trauma-informed practice for open/online higher education. Given survivors’ preference for hybrid and online learning (Werkmeister, 2024), the relative lack of research in this area represents a troubling gap. Particularly concerning is the dearth of scholarly literature that centres survivors, contradicting the fundamental principle of collaboration in a trauma-informed approach.

This session aims to support researchers considering projects that centre adult trauma survivors who learn in open/online settings. Using SAMHSA’s (2014) guidelines for trauma-informed practice, the session dispels myths, dismantles barriers, and provides practical guidance for implementing respectful, collaborative research relations with survivors, ensuring safety for researchers and participants, and attaining institutional research ethics board approval.
:::

### Session 2.3a

#### 11:45 - 12:05 | “Generating” Equity? Why Generative AI-Powered Education Necessitates Integration of Critical Algorithm Studies

**Research**

**Fatima Zohra** | *University of Waterloo*

::: {.callout-note collapse="true"}
### Abstract
To what extent can AI-powered technologies, particularly Generative AI (GenAI), further exacerbate societal inequities? In Ruha Benjamin’s award-winning book, Race After Technology, she conceptualizes “the New Jim Code” as “The employment of new technologies that reflect and reproduce existing inequities but that are promoted and perceived as more objective and progressive than the discriminatory systems of a previous era” (5-6). GenAI is a critical example of a “new technology” that is “computational” – and therefore perceived to be “objective” and “logical” – yet threatens to reinforce the same existing inequities for marginalized people that can weaponize Large Language Models (LLMs) for information warfare. In Artificial Unintelligence, Meredith Broussard argues against “technochauvinism” – the belief that complex problems can always be solved with the right technological solutions – proposing that social issues will not disappear in a digital utopia. Hence, this presentation examines three core areas through which GenAI can pose detrimental harms for society: (1) AI “hallucinations” and mis/disinformation; (2) mass data collection; (3) biased prompt engineering. The examination of these areas builds on existing scholarship on the harms of GenAI (Ferrara, 2024; Mazurczyk et al., 2023; Menczer, 2023) ultimately leading to the proposition that the integration of GenAI in classrooms requires a simultaneous integration of critical algorithm studies so students (and educators) are well-versed in the nuances of GenAI ethics. This is especially pertinent in cases where younger students who may have very limited knowledge of how LLMs work (especially in regard to mass data collection) are increasingly using GenAI for schoolwork. For example, this presentation demonstrates how varied levels of “prompt tuning” can skew generated outputs in LLMs followed by a rhetorical analysis of the broader implications of such nuances in “research” generation – particularly how such manipulation of GenAI models (even inadvertently) can be detrimental for academic research and writing. Thus, this presentation provides practical recommendations for GenAI integration through sample demonstrations, activities, and case studies that can be conducted in the classroom to create awareness of the risks of inequities posed by GenAI thereby underscoring that the promise of GenAI to exponentially increase efficiency and scalability for optimal results across disciplines – including education – must be critically evaluated (Aksoy & Kursun, 2024). The perils of algorithmic discrepancies are echoed by critical algorithm studies scholars who have established that algorithms are becoming increasingly powerful and capable of influencing socio-political change (Benjamin; Noble; O’Neil; Broussard). Ultimately, this presentation provides a novel conceptualization of the implications of GenAI in education through the lens of Open Educational Resources (OER) and Open Educational Practices (OEP) that are increasingly harnessing the power of GenAI to not only generate resources but also evaluate assessments. Examining how such technological infrastructures are (re)shaping pedagogy – and education more broadly – is critical for addressing how the lack of rigorous regulation of these technologies threatens to exacerbate existing inequities and obstruct the democratization of knowledge.
::: 

### Session 2.3b

#### 12:05 - 12:25 | Exploring Students’ Perceptions, Practices, and Training Needs Regarding Generative AI

**Research**

**Marta Samokishyn et al.** | *Saint Paul University*

::: {.callout-note collapse="true"}
### Abstract
The rapid popularity and adoption of generative AI tools are transforming how students learn, research, and create. Generative AI tools, such as ChatGPT, Copilot, and Gemini, are becoming ubiquitous in educational environments, yet little is known about how university students use them. This study investigates students’ use, attitudes, and beliefs surrounding these powerful technologies, aiming to identify critical gaps in understanding, perceived challenges, and necessary training interventions. Our research addresses several key questions: (1) How are students currently utilizing generative AI in their academic work? (2) What are their perceptions of the benefits and risks associated with these tools? (3) What misconceptions or knowledge gaps exist regarding the functionality, limitations, and ethical implications of generative AI? (4) What challenges do students face in effectively and ethically integrating these tools into their learning processes? Finally, (5) what targeted training and support structures are needed to empower students to leverage the potential of generative AI responsibly and effectively? This presentation will provide actionable insights for educators, librarians, and administrators seeking to address students’ use of AI in educational environments and explore what training opportunities would benefit students at this time.
::: 

## 12:45 - 1:00 | Break

## 1:00- 2:30 | Networking
