# Thursday, June 5 {.unnumbered}

## Times listed in this program are Pacific Daylight Time (Victoria, BC) 

:::: {.columns}

::: {.column width="33%"}
<div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
  <div class="card-header"><b><font size="5">Victoria, BC</font></b></div>
  <div class="card-body">
   <div> <iframe src="https://free.timeanddate.com/clock/i9wk0yr8/n1091/fs22/fcfff/tct/pct/ftb/ts1/ta1" frameborder="0" width="168" height="27" allowtransparency="true"></iframe>
</div>
  </div>
</div>

:::

::: {.column width="34%"}
<div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
  <div class="card-header"><b><font size="5">Santa Fe, NM</font></b></div>
  <div class="card-body">
   <div> <iframe src="https://free.timeanddate.com/clock/i9wk0yr8/n231/fs22/fcfff/tct/pct/ftb/ts1/ta1" frameborder="0" width="172" height="27" allowtransparency="true"></iframe>
</div>
  </div>
</div>


:::

::: {.column width="33%"}


<div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
  <div class="card-header"><b><font size="5">Toronto, ON</font></b></div>
  <div class="card-body">
   <div> <iframe src="https://free.timeanddate.com/clock/i9wk0yr8/n250/fs22/fcfff/tct/pct/ftb/ts1/ta1" frameborder="0" width="168" height="27" allowtransparency="true"></iframe>
</div>
  </div>
</div>

:::
::::


## 10:00 - 11:00 PDT | Keynote | Jennifer Wemigwans - Digital Bundles
Remote from Congress in Toronto

::: {.callout-note collapse="true"}
### Abstract
Reflecting Indigenous Knowledge online has the potential to transform education across Canada. In this talk, Dr Wemigwans explores how to ethically present Indigenous Knowledge online through the creation of Digital Bundles. FourDirectionsTeachings.com is an example of a Digital Bundle, an online site where Elders’ Teachings from five distinct First Nations are presented. Digital Bundles represent a way to transform and reframe education by using new technologies to articulate Indigenous Teachings and introduce Canadians to Indigenous epistemologies.
:::

## 11:00 - 11:15 | Break

## 11:15 - 12:15 | Concurrent Session 8

(60 Mins)


### Session 8.1a

**Location: CLE B007**

#### 11:15 - 11:35 | Creating Capacity for Digital Transformation

**Research**

**Leah Macfadyen** | *University of British Columbia*; **Seyyed Kazem Banihashem** | *Open University of the Netherlands* & **Rhiannon Lewis** | *University of British Columbia*

::: {.callout-note collapse="true"}
### Abstract

Globally, the demand for online education has surged, driven by the need for flexible and accessible learning (Johnson, 2023; Quality Matters, 2023) and dramatically escalated by the COVID-19 pandemic (Cui et al. 2022). In 2024, Cui et al. noted that doctoral level education in educational technology will “build critical capacity for leading research and driving transformation in policy and practice”. In this study we contend that while doctoral-level  expertise and leadership is vital, it is widespread access to flexible post-graduate education and training for current and upcoming educators and practitioners that will support system-wide upskilling for ongoing digital transformation. In 2019, and in 2024, we surveyed the global landscape of masters-level education related to educational technologies and digital learning. Currently, 39 institutions offer 65 master’s degree programs in this field. Surprisingly, only eight new master’s degree programs in educational technology launched globally, post-pandemic. However, we did discover extensive curricular rebalancing. Here, we report on the current state of master’s level education in educational technology,  curricular expansions in topic areas that including management, planning and leadership, research methods, technical aspects of design, data and analytics, emerging issues & technologies, and instructional strategies, and we consider how these reflect current educational needs.
:::

### Session 8.2

**Location: CLE B017**

#### 11:15 - 12:05 | Assessment for Equity: Openness and DEI in your grading architecture (WorkShop)

**Workshop**

**Colin Madland** | *University of Victoria* & **Jess Mitchell** | *Ontario College of Art and Design University*

::: {.callout-note collapse="true"}
### Abstract

This workshop will provide an overview of how you can use your grading architecture (how you lead learners through activities that support their learning, and ultimately, how you arrive at a final grade) to support greater equity using openness and DEI in your assessment practice. Equity is compromised when grades are assigned based on anything other than what a learner knows or can do (e.g., arbitrary due dates, punitive policies, etc.). Openness is compromised when learners, instructors, or other stakeholders do not fully understand the meaning and implications of the grades that are assigned. Bring your syllabus and join us as we explore ways to build assessment architectures that ensure grades are assigned according to what learners know and that learners understand how to progress in their learning journey based on the feedback you provide. We will discuss the purposes of assessment, sources of inequity in grading and how to overcome them, effective communication of feedback, instructor workload, and resources to assist you in your journey into alt-grading practices that meet you where you are.
:::

## 12:15 - 1:30 | Lunch

## 1:30 - 2:30 PDT | Keynote | George Veletsianos - What Might/Could/Should Education Look Like in 2035?
Online from Minnesota

::: {.callout-note collapse="true"}
### Abstract
Our societies face economic, demographic, political, environmental, and social challenges, which have resulted in numerous organizations publishing reports calling for brighter education futures. In this interactive keynote, we will envision teaching and learning across diverse contexts in 2035 using a collection of “what if” scenario cards which introduce conundrums, opportunities, and challenges. Through rapid ideation and peer sharing, we will explore multiple education futures, all in the spirit of recognizing the forces that shape and constrain our imagination of what education could be.
:::

## 2:45 - 3:45 | Concurrent Session 9 

(60 Mins)

### Session 9.1a

**Location: CLE B007**

#### 2:45 - 3:05 | The Social Representations of Parents from Rural Backgrounds Regarding the Use and Access to Digital Technologies Among Their Children and Adolescents

<!-- //todo #2 -->

**Research**

**Pascal Gauthier**, **Eve Pouliot** & **Patrick Giroux** | *Université du Québec à Chicoutimi*

::: {.callout-note collapse="true"}
### Abstract
From the very beginning of the COVID-19 pandemic, digital technologies proved to be essential for the functioning of society (INSPQ, 2021). However, behind the apparent "hyperconnectivity" of young people, they are not exempt from digital inequalities (CEFRIO, 2017), and most importantly, they are not innate experts in these technologies (Yagoubi, 2020). Moreover, parents are the closest authority figures to young people regarding the "virtual world" (Reginasari et al., 2021). On the other hand, they may experience a certain ambivalence towards digital technology. Using the conceptual framework of social representations (Moscovici, 1961, 1976), this qualitative research, originating from a master's thesis in social work, analyzes the discourse of 10 parents living in rural areas of Saguenay-Lac-Saint-Jean during the COVID-19 pandemic. The results indicate that they acquired knowledge of videoconferencing, which allowed them to continue their daily lives and ensure their children's education. Some were able to develop a more positive attitude towards technology, while others experienced exhaustion or fatigue related to digital usage. Additionally, parents have a techno-deterministic view of digital technology and remain under the impression that young people have abilities they themselves do not possess (the "digital native" myth). This study can help professionals better understand the digital issues faced by parents and integrate them into their practice, whether in social work or the educational field.
:::

### Session 9.1b

**Location: CLE B007**

#### 3:05 - 3:25 | Digital Learning for Innovative Teaching: Adopting a Competency-Based Approach

**Practice**

**Tanya Elias** | *University of Calgary*

::: {.callout-note collapse="true"}
### Abstract
The Digital Learning Competency Framework developed at Vancouver Community College organizes 21 discrete competencies into three categories and seven sub-categories. Together, these competencies delineate essential digital knowledge, skills and attitudes for instructors and other learning practitioners. Each competency is further defined at four levels of proficiency so that all learning practitioners, regardless of their starting point, can easily engage in meaningful and applied learning paths aligned with their specific needs. These competencies are now being used to develop a Digital Learning For Innovative Teaching (DLIT) microcredential that will offer formal, for credit online learning opportunities with recognition via digital badges and a short certificate. There is also future potential for the Digital Learning Competency Framework, and an associated open challenge bank, to be used to develop and recognize less formal digital learning professional development via portfolio assessment, workshops and other formats. This session discusses the Digital Learning Competency Framework development process, its current uses and the potential to extend its use over time.

:::

### Session 9.2

**Location: CLE B017**

#### 2:45 - 3:35 | Title to Come

**Workshop**

**Valerie Irvine** & **Mariel Miller** | *University of Victoria*

::: {.callout-note collapse="true"}
### Abstract
Forthcoming
:::

## 3:45 - 4:00 | Break

## 4:00 - 5:00 | Concurrent Session 10

(60 mins)

### Session 10.1a

**Location: CLE B007**

#### 4:00 - 4:20 | Exploring the Opportunities and Limitations of Immersive Technologies in Education

**Research**

**Jangchu Tenzin** | *University of New Brunswick*

::: {.callout-note collapse="true"}
### Abstract
The rapid advancement of immersive technologies, including virtual reality (VR), augmented reality (AR), and mixed reality (MR), has transformed educational practices by enhancing engagement, providing interactive learning environments, and enabling the visualization of complex concepts. This presentation examines the opportunities and limitations of these technologies through the lens of media ecology, exploring their effects on pedagogical practices and meaning-making processes. While immersive technologies offer new possibilities for personalized and experiential learning, they also introduce challenges such as cognitive overload, accessibility barriers, and pedagogical biases. Drawing on a comprehensive literature review, this study highlights the dual nature of immersive media as both extensions of human capabilities and potential constraints on traditional learning processes. The findings underscore the need for carefully designed pedagogical frameworks that maximize the benefits of immersive technologies while mitigating their drawbacks. By critically analyzing the role of these tools in education, this presentation contributes to a deeper understanding of how immersive technologies mediate human experience and reshape learning environments. This presentation hopes to engage educators, researchers, and practitioners in critical discussions on the implications of immersive learning technologies, aligning with OTESSA’s focus on openness, technology, and education. It emphasizes the importance of evidence-based approaches to integrating these tools in ways that foster equitable, engaging, and pedagogically sound learning experiences.
::: 

### Session 10.1b

**Location: CLE B007**

#### 4:20 - 4:40 | 3D Printing Resources for the Elementary Classroom

**Research**

**Brittany Johnson** & **Krystal Yang** | *University of Victoria*

::: {.callout-note collapse="true"}
### Abstract
The project focuses on meeting the needs of educators to feel empowered to use digital tools such as 3D printing in their practice. 3D Technology is constantly evolving and there is a current lack of resources and training available to support teachers with 3D printing. Teachers seeking support often search for community; as such the focus of this document and resource are to inform and equip teachers with the necessary skills, confidence and easily implementable lessons and practices. This resource has been shared through an Open Educational resource repository and licensed with Creative Commons, making them widely available and adaptable to teachers, staff, students and the greater learning community. Our research acknowledges digital literacy considerations; Communities of Practice; experiential learning; constructivism; professional development best practices; elementary education, secondary education, and makerspace; and the purpose of 3D printing in elementary are further explored throughout this research paper. Chapter three includes a professional development presentation, pre-workshop activities and understandings of 3D printing, lessons, ready to go activities as well as supplementary handouts for people interested in 3D printing. In order for teachers to feel confident and well supported to put theory into practice, we also designed online forum-style communities that foster communication between users looking for commonalities, solutions, and feedback on their learning. All in all, the goal of our project is to support teachers wanting to implement 3D printing into classrooms and ease the students into technology.
::: 

### Session 10.2

**Location: CLE B017**

#### 4:00 - 4:50 | AI, Oh My! Teaching, Cheating, and Surviving the ChatGPT Era

**Research**

**Jill Robinson**, **Jhotisha Mugon**, **Jessica Rourke** | *University of Victoria*

::: {.callout-note collapse="true"}
### Abstract
The widespread gain in popularity of artificial intelligence, such as ChatGPT, has taken higher education by storm. This has resulted in  instructors adapting their pedagogical approach, feeling pressured to continuously make changes to assessments and the ways in which they engage students. Instructors and students express various sentiments about AI, ranging from positive beliefs and excitement, to fear and uncertainty. In this session we will present concerns about the use of AI in the classroom, challenges to implementation of AI, and solutions focusing on the ethical and pedagogical use of AI in higher education.

Using data from a survey of university instructors, we will present themes from a qualitative analysis of responses to several AI and teaching-related questions, examining such things as familiarity with AI, supports needed for implementation, and trends across courses. We will also consider ethical implications and unintended consequences of technological interventions, emphasizing the importance of aligning digital tools with pedagogical goals. We discuss literature related to student engagement, academic integrity, and the evolving role of AI in education. By combining real-world perspectives from faculty with a critical review of emerging solutions, we aim to provide a balanced perspective on integrating AI technology into teaching pedagogy.
:::

## 5:00 - 5:30 | Travel Break

## 5:30 - Late | Off Site Social Event

**Location: Sticky Wicket Rooftop Patio, Downtown Victoria**

#### Get to Know Each Other

::: 

