# Friday, June 6 {.unnumbered}

## Times listed in this program are Pacific Daylight Time (Victoria, BC) 

:::: {.columns}

::: {.column width="33%"}
<div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
  <div class="card-header"><b><font size="5">Victoria, BC</font></b></div>
  <div class="card-body">
   <div> <iframe src="https://free.timeanddate.com/clock/i9wk0yr8/n1091/fs22/fcfff/tct/pct/ftb/ts1/ta1" frameborder="0" width="168" height="27" allowtransparency="true"></iframe>
</div>
  </div>
</div>

:::

::: {.column width="34%"}
<div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
  <div class="card-header"><b><font size="5">Santa Fe, NM</font></b></div>
  <div class="card-body">
   <div> <iframe src="https://free.timeanddate.com/clock/i9wk0yr8/n231/fs22/fcfff/tct/pct/ftb/ts1/ta1" frameborder="0" width="172" height="27" allowtransparency="true"></iframe>
</div>
  </div>
</div>


:::

::: {.column width="33%"}


<div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
  <div class="card-header"><b><font size="5">Toronto, ON</font></b></div>
  <div class="card-body">
   <div> <iframe src="https://free.timeanddate.com/clock/i9wk0yr8/n250/fs22/fcfff/tct/pct/ftb/ts1/ta1" frameborder="0" width="168" height="27" allowtransparency="true"></iframe>
</div>
  </div>
</div>

:::
::::

<a href="https://chat.opened.ca/signup_user_complete/?id=fk6gcpykkpbqtcdozhxirfptxa&md=link&sbr=su" target="_blank" class="badge bg-success"><b>Link to Mattermost</b></a>


## 9:10 - 10:10 PDT | Presidential Address | Valerie Irvine (UVic) & Stephanie Moore (UNM)
Online in Zoom

<a href="https://uvic.zoom.us/j/89060441105?pwd=DNZMaC4TEl9cbQC1sZpwZLVqxJHFl0.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>



## 10:15 - 11:15 PDT | Keynote | Jean-Paul Restoule - Considerations for Indigenous Centred Online Course Design
Session available in person in HHB 105 & online in Zoom

<a href="https://uvic.zoom.us/j/88276282123?pwd=72eQMU9NM87qrQEa6HGaeNHqbHXEFv.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


::: {.callout-note collapse="true"}
### Abstract
Indigenous people are keen to adopt and adapt technologies for their own uses and purposes yet have less success in controlling and creating technologies that dominate the learning landscape. What are some ways that Indigenous people approach open, distance and digital education? Restoule will share some observations of the potentials, constraints and cautions Indigenous people have expressed regarding online learning, with reference to relationality, authenticity, and learning design.
:::

## 11:15 - 11:30 | Break

## 11:30 - 12:30 | Concurrent Session 11
All sessions also available online in Zoom

### Session 11.1a

<a href="https://uvic.zoom.us/j/88501420433?pwd=9s8bifv0huXWfALgNLqrNIiL1TJl8X.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


**Location: CLE B007**

#### 11:30 - 11:50 | Instructional Design Analytics in Practice: Converting a Multi-Course Graduate Bridging Program from Blended-Synchronous to Blended-Asynchronous Delivery Using Risk-Based and Qualitative Research Techniques

**Practice**

**Deborah Exelby** | *Athabasca University*

::: {.callout-note collapse="true"}
### Abstract
Identifying which synchronous teaching-learning activities in a blended learning program should/could be converted to asynchronous technology-enabled delivery is a real-world problem encountered by many instructional designers.

Risk-based instructional design analytics are an effective, efficient, and evidence-based approach for identifying misaligned learning outcomes and content gaps; appropriate teaching-learning activities; justifiable delivery and interaction methods; and targets to concentrate time, effort, and resources for meeting learning objectives and redesign parameters.

This ‘how to’ presentation will outline a solution for restructuring an existing multi-course higher education program using a risk-based mapping process for curriculum analysis and redesign decision-making. How a current state curriculum was coded, analyzed, and reorganized using triangulation of three sequential techniques is presented: 1) mapping of program (PLO) and course learning outcome (CLO) mastery requirements based on Bloom’s taxonomy (introduce, reinforce, mastery); 2) coding PLO failure risk based on the potential impact of not learning the content to the required mastery level (low, medium, high); and 3) sorting of CLOs based on keywords, into topics (course lessons) and then into themes (courses).

This session demonstrates how instructional design analytics were used successfully in real-world practice to codify and sort existing curricula for program redesign.
:::

### Session 11.1b

<a href="https://uvic.zoom.us/j/88501420433?pwd=9s8bifv0huXWfALgNLqrNIiL1TJl8X.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


**Location: CLE B007**

#### 11:50 - 12:10 | Open Access and the Habitual Use of Crown Photography of Indigenous Children: Ethical Implications

**Research**

**Ivy Shawl-Song** | *Independent*

::: {.callout-note collapse="true"}
### Abstract
The go-to images representing the history of Canada’s Indian Residential Schools (IRS) are of identifiable Indigenous children. As technological advances afford open access to the now digitized photographs, consideration for the child’s right to agency over self is often ignored. Using a social semiotic framework, historical images present alongside paradigmatic relationships to demonstrate the gaps apparent between ethics, Copyright Canada law, child advocacy and social norms. Hundreds of unpublished analogue photographs have passed into provincial and federal archival holdings where copyright remains in perpetuity with the Crown. In cases of academic research and curriculum content design, ethics approval or community engagement are currently not needed when utilizing these images. Many of these children could still be alive today and hold no agency over the photographs. While copyright law serves to protect the creators and users of a photograph, there are no ethical guidelines for the use, dissemination or protection of images of children. This presentation concludes with the demonstration of an interactive reflexive tool developed from the author’s master’s thesis. This tool facilitates ethical consideration beyond the systemic use of ‘Fair Dealing for Educational Purposes’ and may serve to highlight efforts around the privacy and protection of children in research and education.
:::

## 12:30 - 1:45 | Lunch

## 1:45 - 2:05 | Publication Pathways | Michele Jacobsen (UCalgary) & Valerie Irvine (UVic)
Session available online in Zoom & CLE B007/B017 

<a href="https://uvic.zoom.us/j/82225038895?pwd=DrhwC9ge9mD5GnAB5PCrbyam9bmmrz.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


## 2:05 - 2:15 | Break

## 2:15 - 3:15 | Session 12
All sessions also available online in Zoom

### Session 12.1a

<a href="https://uvic.zoom.us/j/87672437008?pwd=vOIN6hQbboY3sROqaLHeTSCe99jbOW.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


**Location: CLE B007**

#### 2:15 - 2:35 | Developing the Technology-integrated Assessment Scale

**Research**

**Colin Madland** | *University of Victoria*, **Valerie Irvine** | *University of Victoria*, **Chris DeLuca** | *Queen’s University* & **Okan Bulut** | *University of Alberta*

::: {.callout-note collapse="true"}
### Abstract
This presentation will highlight the process of building and testing a new scale intended to help researchers understand the Technology-integrated Assessment Framework (TIAF) and how it functions in higher education. In 2024, we published a description of the development of the TIAF (Madland et al., 2024), highlighting four factors related to technology-integrated assessment: (1) assessment purposes, (2) the duty of care owed by instructors to learners, (3) factors influencing technology acceptance, and (4) assessment design. Our current work is focused on understanding how these four factors within the TIAF framework can be operationalized. We will share our process of designing the scale, including defining the key constructs, identifying parameters, and framing parameters as items on the scale. We will also share preliminary results from our pilot study using the first draft of the scale. This session will be of interest to undergraduate and graduate students as well as researchers, faculty members, and administrators seeking to refresh their skills in scale development and anyone interested in assessment in higher education.
:::

### Session 12.1b

<a href="https://uvic.zoom.us/j/87672437008?pwd=vOIN6hQbboY3sROqaLHeTSCe99jbOW.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


**Location: CLE B007**

#### 2:35 - 2:55 | From Mobile Learning to Artificial Intelligence: Evolving UTAUT Constructs in Educational Technology Adoption

**Research**

**Caleb Or** | *Singapore Institute of Technology*

::: {.callout-note collapse="true"}
### Abstract
The Unified Theory of Acceptance and Use of Technology (UTAUT) has played a crucial role in understanding technology adoption in education. This study examines the evolution of UTAUT constructs over three technological periods: the Early Adoption Period (2003–2010), the Mobile and Social Media Boom (2011–2016), and the AI and Digital Transformation Era (2017–Present). Using a one-stage meta-analytic structural equation modelling (OSMASEM) approach, data from 73 studies were analysed to evaluate relationships among key constructs, including Performance Expectancy (PE), Effort Expectancy (EE), Social Influence (SI), Facilitating Conditions (FC), Behavioural Intention (BI), and Use Behaviour (UB). The findings revealed substantial variability across contexts and constructs, with BI consistently emerging as the strongest predictor of UB, underscoring its centrality in technology adoption. The influence of PE on BI increased over time, reflecting advancements in technology that enhanced performance outcomes. The importance of FC in predicting UB also grew, emphasising the role of infrastructure and technical support in adoption. These insights highlight the dynamic nature of UTAUT constructs, providing actionable recommendations for educators, policymakers, and technology developers to align strategies with evolving user needs and expectations in educational contexts. This study reinforces UTAUT’s relevance in addressing contemporary technological challenges.
:::

### Session 12.2a

<a href="https://uvic.zoom.us/j/82738853811?pwd=Oo1VNpQDfOJbPNsc9SNHx3aMBpnbE0.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


**Location: CLE B017**

#### 2:15 - 2:35 | AI Community of Practice

**Practice**

**Mariel Miller** | *University of Victoria*

::: {.callout-note collapse="true"}
### Abstract
Forthcoming
:::

### Session 12.2b

<a href="https://uvic.zoom.us/j/82738853811?pwd=Oo1VNpQDfOJbPNsc9SNHx3aMBpnbE0.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


**Location: CLE B017**

#### 2:35 - 2:55 | The Impact of Sense of Belonging on Emotion Regulation in Online Collaborative Learning: A Cross-Case Comparison of Small Groups

**Research**

**Yeeun Choi** & **Mariel Miller** | *University of Victoria*

::: {.callout-note collapse="true"}
### Abstract
This study explores how a sense of belonging impacts the regulation of emotion in the face of challenge during online collaboration.  A cross-case analysis was conducted between two groups who experienced similar emotions during a negative experience but reported contrasting levels of sense of belonging. Data include video recordings of collaborative exams and post-exam reflections to gain in-depth qualitative insights into learners' perceptions and regulation strategies. By adopting self-regulated learning (SRL) framework, the study seeks to understand how students cope with negative experiences during collaboration, and to what extent their sense of belonging impacts their strategic management of challenges. Findings inform evidence-based guidelines for designing online collaborative learning experiences that not only support students’ emotion regulation but also create supportive online environments.
:::

## 3:15 - 3:30 | Break

## 3:30 - 4:30 | Insight Spotlight

**Location: CLE A127**

<a href="https://uvic.zoom.us/j/81550118613?pwd=fHuZPB2gi1eDCVUa60i9KaUaZQEbmE.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


#### Facilitated Synthesis of Insights from Across the Conference, Culminating in Forward-Looking Actions to Tackle our Biggest Challenges and Grand Challenges

**Valerie Irvine** & **Mariel Miller** | *University of Victoria*

## 4:30 - Late |  Off Site Social Event

**Location: TBD**

#### Closing Celebration

