# Tuesday, June 3 {.unnumbered}

## Times listed in this program are Pacific Daylight Time (Victoria, BC) 

:::: {.columns}

::: {.column width="33%"}
<div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
  <div class="card-header"><b><font size="5">Victoria, BC</font></b></div>
  <div class="card-body">
   <div> <iframe src="https://free.timeanddate.com/clock/i9wk0yr8/n1091/fs22/fcfff/tct/pct/ftb/ts1/ta1" frameborder="0" width="168" height="27" allowtransparency="true"></iframe>
</div>
  </div>
</div>

:::

::: {.column width="34%"}
<div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
  <div class="card-header"><b><font size="5">Santa Fe, NM</font></b></div>
  <div class="card-body">
   <div> <iframe src="https://free.timeanddate.com/clock/i9wk0yr8/n231/fs22/fcfff/tct/pct/ftb/ts1/ta1" frameborder="0" width="172" height="27" allowtransparency="true"></iframe>
</div>
  </div>
</div>


:::

::: {.column width="33%"}


<div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
  <div class="card-header"><b><font size="5">Toronto, ON</font></b></div>
  <div class="card-body">
   <div> <iframe src="https://free.timeanddate.com/clock/i9wk0yr8/n250/fs22/fcfff/tct/pct/ftb/ts1/ta1" frameborder="0" width="168" height="27" allowtransparency="true"></iframe>
</div>
  </div>
</div>

:::
::::


## 10:00 - 11:00 PDT | Keynote | James Slotta - Critical Action Learning: Empowering Students with Meaning and Purpose in 21st Century Classrooms
Session available online in Zoom & HHB 105. 

<a href="https://uvic.zoom.us/j/83887491824?pwd=2Gs32IiEqbbk9dpz2sho3gTRlaniFN.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>



::: {.callout-note collapse="true"}
### Abstract
This presentation will review my previous work in pedagogies for learning communities, including the use of “smart classroom” technologies to support collective inquiry and scaffold students and teachers. It will then introduce Critical Action Learning, as an international professional learning community of teachers. I will present the CALE design framework, pedagogical approaches, and present several examples of teacher enactments. I will also discuss new roles for physical classroom space and technology environments.
:::

## 11:00 - 11:15 | Break

## 11:15 - 12:15 | Concurrent Session 3
All sessions available online in Zoom & CLE B007/B017. 

### Session 3.1

<a href="https://uvic.zoom.us/j/82285881523?pwd=bdoiIU9mg23xag0BNo6jBea7XlgbmB.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


#### 11:15 - 12:05 | Integrating Artificial Intelligence into a Community of Inquiry: The Roles of AI

**Practice**

**Hyeyung Park** | *Athabascau University*

::: {.callout-note collapse="true"}
### Abstract
The Fifth Industrial Revolution (5IR) highlights the collaboration between humans and technology, emphasizing sustainability, human-centeredness, and environmental responsibility. Artificial intelligence (AI) is a transformative force reshaping instructional design by partnering with learners, addressing individual needs, and fostering personalized learning. This research explores AI applications in instructional design and strategies to overcome challenges in AI integration. Using a three-level model as a learning theory, it examines the roles of AI for individual, team and organizational learning. Furthermore, this study provides practical insights for integrating AI into a community of inquiry (CoI) framework to enhance learning design. The dearth of research on the roles of AI within the CoI framework has made it difficult for practitioners to employ AI in instructional strategies effectively. This paper addresses this gap by proposing AI roles grounded in a three-level model and offering practical insights on integrating AI into a CoI framework. Ultimately, it empowers practitioners to leverage AI effectively, maximize its potential benefits, and address challenges proactively through a theory-informed approach.
:::

### Session 3.2a

<a href="https://uvic.zoom.us/j/81381479887?pwd=cYgsMcUMvQax8ythkOW7nKX2Q4JkBG.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


#### 11:15 - 11:35 | Addressing the Assumption that Online Learning is Intuitive: An OER for Learning to Learn Online

**Practice**

**Kristin Petrovic et al.**, **Lynn Corcoran**, **Emily Doyle** & **Terra Murray** | *Athabascau University*

::: {.callout-note collapse="true"}
### Abstract
Primary and secondary schooling in North America is generally situated around the traditional model of in-person teaching and learning. As such, when entering post-secondary education, most people already have a sense of how to learn in the place-based setting. However, if moving to a different mode of education, such as the online environment, it is essential to support the necessary shift in understanding how to learn within this context.

To meet the needs of those learning to learn online, faculty from programs including Counseling Psychology and Undergraduate and Graduate Nursing in the Faculty of Health Disciplines at Athabasca University collaborated to adapt an e-book open educational resource (OER) to facilitate how to adjust and thrive in the online learning environment.

In this presentation, we share the overall aim of adapting this OER, the main topics addressed in the e-book, as well as processes and practices that the faculty implemented as they collaborated to develop and adapt this resource. Finally, we share recommendations related to supporting learners to learn online as well as our strategies for addressing the pragmatic aspects of adapting an OER for use across different programs in an online post-secondary environment.
:::

### Session 3.2b

<a href="https://uvic.zoom.us/j/81381479887?pwd=cYgsMcUMvQax8ythkOW7nKX2Q4JkBG.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


#### 11:35 - 11:55 | Creating Whiteboard Animations to Explain Tooth Microanatomy

**Practice**

**Nazlee Sharmin** & **Ava K Chow** | *University of Alberta*

::: {.callout-note collapse="true"}
### Abstract
The knowledge of tooth microanatomy is a cornerstone of dental education. However, teaching this complex concept in an engaging manner is challenging for many educators. The rapid development of digital instructional tools has enormous potential for the design and development of engaging and effective teaching resources; whiteboard animation is one of them. Whiteboard animation is a style of animated video where the content appears to be hand-drawn on a whiteboard and narrated in a storytelling manner. This technique has the benefits of traditional animations, with the added ability to combine visual thinking and storytelling.

We have used a graphics editor, Procreate, and an animation maker, VideoScribe to create whiteboard animations for the students in the Doctor of Dental Surgery (DDS) program at the University of Alberta. An anonymous survey was also conducted to explore students’ experiences with the animations as learning tools. Fifty-three percent of the DDS class (n = 17) participated in the survey. Most survey participants (82%) agreed or strongly agreed that the whiteboard animations helped clarify concepts for them.
:::

### Session 3.2c

<a href="https://uvic.zoom.us/j/81381479887?pwd=cYgsMcUMvQax8ythkOW7nKX2Q4JkBG.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


#### 11:55 - 12:15 | Developing a Mobile App for Oral Histology

**Practice**

**Nazlee Sharmin**, **Hady Abdallah**, **Elias Jirgees** & **Ava K Chow** | *University of Alberta*

::: {.callout-note collapse="true"}
### Abstract
m-Learning is gaining popularity in health professional education; however, reports on mobile apps targeting didactic teaching and learning of histology are scarce. Histology is an essential foundational component of dental and medical education. At the Mike Petryk School of Dentistry, University of Alberta, instructors use photomicrographs from textbooks to teach students the microanatomy of teeth, the development of tooth and facial regions, and developmental anomalies. The lack of high-quality tissue sections and insufficient class time challenge both students and instructors. To provide students with an accessible collection of diverse histological sections and to facilitate in-class didactic teaching, we developed an Augmented Reality (AR)-based mobile app called Tooth ARcademy. This app has three modes. The instructors can use the AR-based Learn mode to create in-class activities and supplemental questions for students with specific learning outcomes. The Practice mode enables students to study oral histology outside of class time. With the Quiz mode of Tooth ARcademy, students can self-assess their knowledge of oral histology by participating in quizzes. The knowledge of histology is essential for dental education. We believe Tooth ARcademy will be a valuable m-learning tool benefiting dental students and educators.
:::

## 12:15 - 12:45 | Break

## 12:45 - 1:45 | Concurrent Session 4 
All sessions available online in Zoom & CLE B007/B017. 

### Session 4.1a

<a href="https://uvic.zoom.us/j/84292463878?pwd=8phqf6wQYo2Wy6mm0Wvaha0szd3baT.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


#### 12:45 - 1:05 | Mid-American Conference Websites and Student Well-Being: A Content Analysis

**Research**

**Hui Zhan** | *Ohio University*

::: {.callout-note collapse="true"}
### Abstract
This study examines how the twelve universities within the Mid-American Conference (MAC) use their websites to communicate the components of well-being outlined in the inter-association definition. Using content analysis, the findings show that institutions prioritize aspects of individual well-being, such as happiness and self-esteem, alongside community-oriented themes like inclusivity and shared purpose. However, the analysis also highlights inconsistencies, with some universities excelling in areas like subjective well-being while underemphasizing civic engagement and systemic equity. These results underline the importance of a more balanced approach to presenting well-being initiatives online. Future efforts should focus on refining digital communication strategies to align institutional well-being goals more closely with the inter-association framework, ensuring a more comprehensive and cohesive representation of student and community well-being.
:::

### Session 4.1b

<a href="https://uvic.zoom.us/j/84292463878?pwd=8phqf6wQYo2Wy6mm0Wvaha0szd3baT.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


#### 1:05 - 1:25 | How Are Post-Secondary Educators Navigating the AI Revolution?

**Research**

**Adam Vanzella Yang** | *The Conference Board of Canada*

::: {.callout-note collapse="true"}
### Abstract
Generative artificial intelligence (AI) promises to reshape how we teach and learn. Yet, little is known about how educators are navigating the AI revolution. In this study, we discuss findings from a national survey of post-secondary educators in Canada (N=402). We found that most educators have neither explicitly permitted nor prohibited student use of AI tools. Notably, 80% reported not receiving any formal guidance or training from their institutions. There is a strong demand for professional development in this area, with educators seeking training for both themselves and their students. Key concerns about generative AI include its potential for facilitating cheating, the submission of unoriginal work, and its impact on students’ critical thinking and independent learning. However, educators are more open to the use of AI for secondary tasks such as translation, general research and knowledge acquisition, and grammar assistance. Educators who use generative AI more frequently tend to be more optimistic about its potential, although they remain wary of its ethical implications and possible threats to the integrity and reliability of knowledge. Overall, educator attitudes toward AI are complex and multifaceted. To effectively integrate AI, institutions must consider the diverse needs of different disciplines, professional practices, and individual experiences with this technology.
:::

### Session 4.2

<a href="https://uvic.zoom.us/j/83501621211?pwd=RYsTfnciMYubnQzibFPf8YbqzCcIY7.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


#### 12:45 - 1:45 | Designing Calm: Reducing Learner Anxiety with H5P in Digital OER Textbooks

**60 Minute Workshop**

**Theresa Huff** | *Loyola Marymount University*

::: {.callout-note collapse="true"}
### Abstract
Anxiety in online learning is a significant barrier to student success, yet thoughtful design of digital course materials can foster a more inclusive and supportive environment. In this interactive workshop, participants will explore how H5P, a free and open-source tool, can be used to reduce learner anxiety through accessible, visually engaging content, formative activities, and reflective practices in digital OER textbooks.

Grounded in original research findings, this session will highlight how applying multimedia principles—such as segmenting, emotional design, feedback, and generative activities—can meaningfully lower learner anxiety. Participants will examine examples of course materials that integrate H5P for diverse purposes, including presenting content visually, promoting deeper reflection, and supporting active engagement. A hands-on segment will guide attendees through creating their own H5P types, with options to follow along or observe. Discussions will center on how these techniques build supportive, inclusive, and calm digital learning spaces, fostering a sense of togetherness by addressing common learner challenges.

By the end of this session, attendees will gain actionable design principles, practical H5P techniques, and strategies for rethinking instructional design to support student well-being in online learning environments.
:::

## 1:45 - 2:00 | Break

## 2:00 - 3:00 | Concurrent Session 5
All sessions available online in Zoom & CLE B007/B017. 

### Session 5.1

<a href="https://uvic.zoom.us/j/85833151185?pwd=WIY6T5AvMub2lIyo7c6gFn2zBETqG8.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


#### 2:00 - 2:50 | Speculation: Shaping the Future of Education

**Practice**

**Danielle Dilkes** |  *Western University*

::: {.callout-note collapse="true"}
### Abstract
Speculation is a powerful tool for shaping the future and has significant potential in education. This workshop will introduce the concept of speculative storytelling, drawing heavily on the work of Octavia Butler (2000) and Donna Haraway (2021) as well as speculative design methodologies (Dunne & Raby, 2013), future-making from design anthropology (Akama et al., 2018) and speculative education fiction from critical education studies (Houlden & Veletsianos, 2023; Krutka et al., 2021). We will look at how speculation has been used in various contexts as a tool for future-making and design and discuss specifically how it can be a useful tool for creating the futures that we want (and need) in higher education.

Participants will engage in reflection and micro-storytelling activities throughout the session, providing them with tools for speculative thought and empowering them to contribute to future-making in their own contexts.
:::

### Session 5.2

<a href="https://uvic.zoom.us/j/85870409429?pwd=v2KtYJ7MKhcEicmqjtCeLdSVOXvdu8.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


#### 2:00 - 2:50 | Transformative Digital Accessibility and Post-Secondary Teaching Praxis

**Workshop or Demo**

**Kim Ashbourne** & **Michael Paskevicius** | *University of Victoria*

::: {.callout-note collapse="true"}
### Abstract
Digital accessibility is more than a technical/compliance issue. It is a dynamic sociocultural phenomenon that occurs when people with disabilities, and those using assistive technologies, can equitably and agentively: find, understand, navigate, engage in, and contribute to information sharing, information production, and sociocultural experience sharing in digital environments with others (Author, 2025; Web Accessibility Initiative, n.d.) The technical/compliance framing typically encountered in post-secondary has done educators and learners a disservice by focusing on the “requirements” rather than on inclusion and transformative learning experiences.

What might change if we as educators set aside the technical/compliance lens and look at digital accessibility through a pedagogical lens? This workshop builds on two emergent themes in literature exploring pedagogical considerations relative to digital accessibility. Theme #1: There is a small but growing body of research pointing us toward a transformative digital accessibility praxis (Author, 2025). Theme #2 A transformative digital praxis can be motivated by your personal pedagogical approach (Melonçon, 2018; Oswal & Melonçon, 2017). This interactive workshop will draw on liberatory pedagogical perspectives and a Disability Justice lens. Participants will leave with tools to build a personal plan to develop a pedagogically-motivated, transformative digital accessibility praxis.
:::
