# Monday, June 17 {.unnumbered}

::: {.callout-tip}
## Note!
Online Only. All times Eastern Daylight Time.
:::

## Current time in Montréal (click for more info)

<iframe src="https://free.timeanddate.com/clock/i98z8zgl/n165/fs18/tcccc/ftbi/tt0/tw1/tm1/ta1" frameborder="0" width="347" height="23">

</iframe>

<!--

> Join us at the #OTESSA24 Morning Radio Show Monday, Tuesday, Wednesday, May 29, 30, and 31 from 6:30 – 7:30 am (Eastern) at https://voiced.ca

-->

## 11:00 - 11:30 | Co-Located Shared Meet-Up | Drop-In


## 11:30 - 12:00 | Conference Welcome, Announcements, & Land Acknowledgement

## 12:00 - 1:00 | Keynote

**Speaker** | *Forthcoming*

## 1:00 - 1:15 | Break

## 1:15 - 2:45 | Concurrent Session 17

### Session 17.1 | Transitions of Online Learning and Teaching

#### 1:15 - 2:15 | Procurement and Vendor Relations as Leverage Points for Ethics in Ed Tech 

**Practice**

**Stephanie Moore & Heather Tillberg-Webb** | *University of New Mexico*


::: {.callout-note collapse="true"}
## Abstract

Practitioners are not always in a design role or design-only role but also in roles where technology selection, procurement, and implementation are primary tasks. Procurement and technology selection processes can be significant leverage points for integrating ethical considerations – such as accessibility, data rights, and privacy – into educational technology decision making through selection and purchasing. Doing so often relies on the nature of the relationship that instructional design and academic tech teams have with vendors, and those relationships can vary greatly from one vendor to another.

This session will explore experiences with various vendors and examples of how dialogue and collaboration with a responsive vendor can impact learning and non-learning related outcomes, and can save a project. We will also explore examples where breakdowns in review and procurement processes or communications with a vendor had deleterious outcomes for implementing an ed tech product into the learning ecosystem. These examples and non-examples help to identify particular points in the process of dealing with vendors from standards development to procurement to implementation to on-going partnerships and also discuss multi-party vendor relationships. We will share examples from our own current and previous experiences in various roles across our careers as a VP of academic technology, Director of Instructional Design, and instructional designers (see Appendix A). We will also invite session participants to share examples from their own work.

:::

#### 2:15 - 2:45 | Connecting Threads: Exploring the Link between Academic Helpseeking and Student Sense of Belonging in Online Learning 

**Research**

**Lawrence Armo Biney & Mariel Miller** |  *University of Victoria*

::: {.callout-note collapse="true"}
## Abstract
Students’ sense of belonging and their ability to engage in adaptive help-seeking are key factors to consider when supporting online, post-secondary learning. However, to date, few studies have examined how these factors intertwine to support academic performance in online learning environments. Using a theoretical framework of self-regulated learning, this study explores the relationship between students' self-reported sense of belonging in an online learning tutorial and their engagement in adaptive and maladaptive help-seeking behaviors in the course. The participants were undergraduate students in a first-year, hybrid course. Sense of belonging was assessed using the sense of belonging subscale in the Perceived Cohesion scale. Academic help-seeking was measured using a scale adapted from Karabenick (2004) and Han (2014). Results are presented using descriptive statistics and a correlation matrix. These preliminary findings are the first steps in a larger MA thesis, which aims to contribute to a broader understanding of the interplay between a sense of belonging and help-seeking in online classrooms, paving the way for the design of supportive online learning.

:::

### Session 17.2 | Addressing Inequities


#### 1:15 - 2:15 | Reflections on a Canadian Framework for Indigenous Open Education Development 

**Practice**

**Brad Wuetherick & Kayla Larson** | *University of British Columbia*

::: {.callout-note collapse="true"}
## Abstract

Facilitated by two Indigenous scholars (both of Métis and European ancestry), this session delves into insights gleaned from the Indigenous OER Summit 2024 held earlier this year at the University of British Columbia. In February 2024, a collective effort amongst Indigenous parties interested in open education, composed of students, faculty, and librarians, laid the groundwork for a Canadian framework outlining best practices for Indigenous open educational resource (OER) development. This presentation sheds light on the day's proceedings, emphasizing collaborative processes, discoveries, and outcomes. The conversation extends to post-summit initiatives, focusing on refining documentation and gathering feedback on the framework. Attendees can anticipate a thorough exploration of summit activities, the subsequent steps in framework development, and the plans for additional feedback. The presenters will also share their strategy for disseminating the framework. Moreover, the session outlines future national advocacy plans in support of Indigenous OER development. A substantial portion of the session will be dedicated to group discussion and audience feedback on the framework process and its details, by eliciting response to a series of questions posed by the presenters.

:::

#### 2:15 - 2:45 | Role of Social Media in Addressing Educational Inequality: A Critical Examination of Marginalized Teens’ Social Media Usage

**Research**

**Daeun Jung** | *Florida State University*

::: {.callout-note collapse="true"}
## Abstract
Although digital technology is valorized for its promises in empowering individual learners and democratize educational opportunities, such hopeful imaginaries need to be critically revisited. What is the role of social media in addressing educational inequality? This study aims to unravel the question by examining the role of social media in the college choice system of potential first-generation college students. The study adopts a multiple case study approach, engaging with eleven high school seniors, whose parents did not complete a 4-year college/university. Two interviews and a week of social media diary data were collected. The themes revealed the teens’ contradictory views toward the role of social media in their college choice system: (1) abundant but insufficient information, (2) helpful but not impactful for college choice, and (3) inspiring but distressing experiences. The contradictions uncover the important role of the in-person support system and resources embedded in marginalized teens’ college choice system, underscoring the pre-existing inequalities in their social contexts. Based on the results, I critically discuss the role of social media in addressing educational inequality, particularly the optimism around digital informal learning, and provide suggestions for formal schooling to enhance marginalized teens’ college access.

:::

### Session 17.3 | Wildcard
#### 1:15 - 2:15 | Breaking Down Barriers: Using Docsify-This As an Entry Point to Markdown Open Publishing

**Workshop** 

**Paul Hibbitts** | *Hibbitts Design*

::: {.callout-note collapse="true"}
## Abstract
The open-source project Docsify-This (public instance at <https://docsify-this.net>) aims to help open educators and publishers overcome barriers to using Markdown content for publishing and sharing open educational resources. With Docsify-This, users can leverage Markdown's ubiquitous and system-independent format without needing to set up their own website, while keeping full control (including original location) of their source content.

Along with the benefits of using Markdown content for open publishing, significant technical barriers have often existed such as required platform configurations and build processes. And, once content is published, displaying it within other platforms and contexts is not easily accomplished. But with Docsify-This, any publicly available Markdown file can be instantly turned into a responsive standalone web page, and multiple Markdown files can even be linked together to provide a complete website. Individual Docsify-This generated Web pages can also be seamlessly embedded and visually re-styled into other platforms.

Further details about the process used to publish open content with Docsify-This will be shared, along with examples, demonstrations and a range of online activities, for those interested in innovations and educational equity related Open Educational Practices.
:::

#### 2:15 - 2:45 | Application of Interactive H5P Learning Content in a Dental Hygiene Course

**Practice** 

**Nazlee Sharmin & Ava K. Chow** | *University of Alberta*

::: {.callout-note collapse="true"}
## Abstract
The educational experience in the Dental Hygiene Program consists of didactic lectures, simulation labs, and clinical experiences. Although the recent surge of curriculum renovation in dental and medical schools centers around enhancing student engagement and active learning, didactic teaching remains teacher-focused, involving students as passive learners only. H5P is an open platform for creating and sharing interactive HTML5 learning content. Oral biology (OBIOL 302) is a foundational science course offered to third-year students in the Dental Hygiene (DH) program. A large set of H5P content was created and provided to students through the learning management system as supplementary material. A study was conducted to evaluate the impact of these interactive H5P contents on students’ learning experiences. Anonymized student performance data from the summative exam were analyzed, and a survey was administered. Students performed better in questions for which H5P supplements were provided. The results from the survey showed satisfaction and perceived benefit of using H5P as supplementary content in didactic lectures. Students appreciated the content’s interactive nature and expressed willingness to have similar experiences in our courses. Our findings indicate that the H5P platform has the potential to redefine didactic teaching by fostering an active learning environment.

:::

## 2:45 - 3:00 | Break

## 3:00 - 3:45 | Concurrent Session 18 | Forthcoming

## 3:45 - 4:00 | Break

## 4:00 - 4:30 | Social Guest 

## 4:30 - 5:00 | Discussion/Networking Pod Drop-In

